default[:postfix][:relayhost] = 'smtp.mailgun.org'
default[:postfix][:smtp][:login] = ''
default[:postfix][:smtp][:password] = ''
default[:postfix][:mynetworks_style] = 'host'
default[:postfix][:inet_interfaces] = 'loopback-only'
