default[:postfix][:relayhost] = 'smtp.mailgun.org'
default[:postfix][:smtp][:login] = ''
default[:postfix][:smtp][:password] = ''
default[:postfix][:mynetworks_style] = 'host'
default[:postfix][:mynetworks] = '127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128'
default[:postfix][:inet_interfaces] = 'loopback-only'
